-- [전체 스키마 + 업데이트]
-- 이 스크립트는 테이블이 없으면 새로 만들고, 이미 있으면 누락된 컬럼만 추가합니다.

-- 1. 가게 정보 테이블
create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null,
  lat float not null,
  lng float not null,
  address text,
  naver_place_id text unique,
  is_open boolean default true
);

-- 2. 상품 정보 테이블 (재고/가격 + 사장님 인증 정보)
create table if not exists products (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  price int default 0,
  status text default 'UNKNOWN',
  last_check_time timestamp with time zone default timezone('utc'::text, now()),
  
  -- 새로 추가된 컬럼들 (테이블 생성 시 포함됨)
  stock_count INTEGER DEFAULT 0,
  owner_id UUID REFERENCES auth.users(id),
  business_reg_no TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  is_verified BOOLEAN DEFAULT FALSE
);

-- 3. 사용자 제보 테이블
create table if not exists user_reports (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id),
  report_type text check (report_type in ('HAVE', 'NO_HAVE')),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- [중요] 기존 테이블이 이미 존재할 경우를 대비한 컬럼 추가 명령어 (에러 방지용 IF NOT EXISTS 포함)
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_count INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS business_reg_no TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_products_owner_id ON products(owner_id);

-- 4. 권한 설정 (RLS)
-- 기존 정책이 있으면 에러가 날 수 있으므로, 없을 때만 생성하도록 하거나 에러를 무시하세요.
alter table stores enable row level security;
alter table products enable row level security;
alter table user_reports enable row level security;

-- 정책 생성 (이미 존재한다는 에러가 나면 무시해도 됩니다)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'stores' AND policyname = 'Enable read access for all users') THEN
        create policy "Enable read access for all users" on stores for select using (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'stores' AND policyname = 'Enable insert access for all users') THEN
        create policy "Enable insert access for all users" on stores for insert with check (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Enable read access for all users') THEN
        create policy "Enable read access for all users" on products for select using (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Enable insert access for all users') THEN
        create policy "Enable insert access for all users" on products for insert with check (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Enable update access for all users') THEN
        create policy "Enable update access for all users" on products for update using (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_reports' AND policyname = 'Enable read access for all users') THEN
        create policy "Enable read access for all users" on user_reports for select using (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_reports' AND policyname = 'Enable insert access for all users') THEN
        create policy "Enable insert access for all users" on user_reports for insert with check (true);
    END IF;
END $$;