-- 사장님 포스트 기능 추가

-- 1. 이미지 저장소 버킷 생성 (Supabase Storage)
-- Supabase Dashboard > Storage에서 수동으로 'store-photos' 버킷을 생성하거나,
-- 다음 SQL로 생성할 수 있습니다 (권한 설정 필요):
-- insert into storage.buckets (id, name, public) values ('store-photos', 'store-photos', true);

-- 2. 사장님 포스트 테이블 생성
CREATE TABLE IF NOT EXISTS store_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES stores(id) ON DELETE CASCADE NOT NULL,
    owner_id UUID NOT NULL, -- 작성자 (supabase auth user)
    content TEXT, -- 포스트 내용
    photos TEXT[], -- 사진 URL 배열 (최대 5장)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS idx_store_posts_store_id ON store_posts(store_id);
CREATE INDEX IF NOT EXISTS idx_store_posts_created_at ON store_posts(created_at DESC);

-- 4. RLS (Row Level Security) 정책
ALTER TABLE store_posts ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 (있으면)
DROP POLICY IF EXISTS "Anyone can view store posts" ON store_posts;
DROP POLICY IF EXISTS "Owners can create their posts" ON store_posts;
DROP POLICY IF EXISTS "Owners can update their posts" ON store_posts;
DROP POLICY IF EXISTS "Owners can delete their posts" ON store_posts;

-- 누구나 포스트를 읽을 수 있음
CREATE POLICY "Anyone can view store posts"
    ON store_posts FOR SELECT
    USING (true);

-- 인증된 사용자만 자기 포스트를 작성할 수 있음
CREATE POLICY "Owners can create their posts"
    ON store_posts FOR INSERT
    WITH CHECK (auth.uid() = owner_id);

-- 본인의 포스트만 수정/삭제 가능
CREATE POLICY "Owners can update their posts"
    ON store_posts FOR UPDATE
    USING (auth.uid() = owner_id);

CREATE POLICY "Owners can delete their posts"
    ON store_posts FOR DELETE
    USING (auth.uid() = owner_id);
